In [2]:
import pandas as pd 
import numpy as np 
coffee= pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
results=pd.read_parquet('./data/results.parquet')

In [6]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [8]:
olympics=pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')

In [10]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [11]:
bios=pd.read_csv('./data/bios.csv')

In [12]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [13]:
bios.loc[0:10,["name"]]

                       name
0     Jean-François Blanchy
1            Arnaud Boetsch
2              Jean Borotra
3           Jacques Brugnon
4              Albert Canet
5         Nicolas Chatelain
6             Patrick Chila
7              Henri Cochet
8             Marcel Cousin
9        Guy de la Chapelle
10  Élie, Comte de Lastours

In [14]:
olympics.iloc[3:15,[1,2,3]]

      type discipline                     event
3   Summer     Tennis  Doubles, Mixed (Olympic)
4   Summer     Tennis    Doubles, Men (Olympic)
5   Summer     Tennis    Singles, Men (Olympic)
6   Summer     Tennis    Doubles, Men (Olympic)
7   Summer     Tennis    Singles, Men (Olympic)
8   Summer     Tennis  Doubles, Mixed (Olympic)
9   Summer     Tennis    Doubles, Men (Olympic)
10  Summer     Tennis    Singles, Men (Olympic)
11  Summer     Tennis    Doubles, Men (Olympic)
12  Summer     Tennis    Doubles, Men (Olympic)
13  Summer     Tennis    Singles, Men (Olympic)
14  Summer     Tennis  Doubles, Mixed (Olympic)

In [16]:
olympics.iloc[0:10, 1:4]

     type discipline                     event
0  Summer     Tennis    Singles, Men (Olympic)
1  Summer     Tennis    Doubles, Men (Olympic)
2  Summer     Tennis    Singles, Men (Olympic)
3  Summer     Tennis  Doubles, Mixed (Olympic)
4  Summer     Tennis    Doubles, Men (Olympic)
5  Summer     Tennis    Singles, Men (Olympic)
6  Summer     Tennis    Doubles, Men (Olympic)
7  Summer     Tennis    Singles, Men (Olympic)
8  Summer     Tennis  Doubles, Mixed (Olympic)
9  Summer     Tennis    Doubles, Men (Olympic)

In [22]:
results.at[10,"athlete_id"]

np.int64(4)

In [ ]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN