In [2]:
import pandas as pd 
import numpy as np 
coffee= pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [5]:
results=pd.read_parquet('./data/results.parquet')

In [6]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [8]:
olympics=pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')

In [10]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [11]:
bios=pd.read_csv('./data/bios.csv')

In [12]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [13]:
bios.loc[0:10,["name"]]

                       name
0     Jean-François Blanchy
1            Arnaud Boetsch
2              Jean Borotra
3           Jacques Brugnon
4              Albert Canet
5         Nicolas Chatelain
6             Patrick Chila
7              Henri Cochet
8             Marcel Cousin
9        Guy de la Chapelle
10  Élie, Comte de Lastours

In [14]:
olympics.iloc[3:15,[1,2,3]]

      type discipline                     event
3   Summer     Tennis  Doubles, Mixed (Olympic)
4   Summer     Tennis    Doubles, Men (Olympic)
5   Summer     Tennis    Singles, Men (Olympic)
6   Summer     Tennis    Doubles, Men (Olympic)
7   Summer     Tennis    Singles, Men (Olympic)
8   Summer     Tennis  Doubles, Mixed (Olympic)
9   Summer     Tennis    Doubles, Men (Olympic)
10  Summer     Tennis    Singles, Men (Olympic)
11  Summer     Tennis    Doubles, Men (Olympic)
12  Summer     Tennis    Doubles, Men (Olympic)
13  Summer     Tennis    Singles, Men (Olympic)
14  Summer     Tennis  Doubles, Mixed (Olympic)

In [16]:
olympics.iloc[0:10, 1:4]

     type discipline                     event
0  Summer     Tennis    Singles, Men (Olympic)
1  Summer     Tennis    Doubles, Men (Olympic)
2  Summer     Tennis    Singles, Men (Olympic)
3  Summer     Tennis  Doubles, Mixed (Olympic)
4  Summer     Tennis    Doubles, Men (Olympic)
5  Summer     Tennis    Singles, Men (Olympic)
6  Summer     Tennis    Doubles, Men (Olympic)
7  Summer     Tennis    Singles, Men (Olympic)
8  Summer     Tennis  Doubles, Mixed (Olympic)
9  Summer     Tennis    Doubles, Men (Olympic)

In [22]:
results.at[10,"athlete_id"]

np.int64(4)

In [ ]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [28]:
bios.sort_values("height_cm").head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN
48662,49016,Nadia Fezzani,NaN,NaN,NaN,NaN,Libya,131.0,41.0,NaN
28105,28315,Ana Manso,1966-03-07,Tarragona,Tarragona,ESP,Spain,132.0,31.0,NaN
43257,43591,Said Al-Khatry,1947-01-01,NaN,NaN,NaN,Oman,132.0,66.0,NaN
35826,36109,Michael Conway,1953-03-03,Sydney,New South Wales,AUS,Canada,132.0,48.0,NaN
43259,43593,Khamis Al-Subhi,1954-01-01,NaN,NaN,NaN,Oman,132.0,58.0,NaN
4776,4794,Gabriel Ogun,1946-06-10,Epe,Lagos,NGR,Nigeria,133.0,48.0,NaN
126881,129286,Flávia Saraiva,1999-09-30,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,133.0,31.0,NaN
28762,28976,Choi Myong-Hui,1966-06-13,NaN,NaN,NaN,Democratic People's Republic of Korea,135.0,25.0,NaN
4505,4520,Peter Ayesu,1962-06-01,NaN,NaN,NaN,Malawi,135.0,51.0,NaN
101552,102450,Jana Labáková,1966-01-26,Detva,Banská Bystrica,SVK,Czechoslovakia,135.0,34.0,NaN
28042,28252,Lu Li,1976-08-30,Changsha,Hunan,CHN,People's Republic of China,136.0,30.0,NaN
90538,91261,Crystal Gilmore,1983-04-08,Cambridge,Ontario,CAN,Canada,136.0,47.0,NaN
28968,29182,Mariya Filatova,1961-07-19,Leninsk-Kuznetsky,Kemerovo,RUS,Soviet Union,136.0,30.0,NaN
28958,29172,Liubov Sheremeta,1980-01-17,Lviv,Lviv,UKR,Ukraine,136.0,30.0,NaN
16507,16623,Stanley Smith,1952-08-20,NaN,NaN,NaN,Barbados,136.0,54.0,NaN

In [37]:
bios.sort_values(["height_cm", "weight_kg"],ascending=[1, 0]).head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN
48662,49016,Nadia Fezzani,NaN,NaN,NaN,NaN,Libya,131.0,41.0,NaN
43257,43591,Said Al-Khatry,1947-01-01,NaN,NaN,NaN,Oman,132.0,66.0,NaN
43259,43593,Khamis Al-Subhi,1954-01-01,NaN,NaN,NaN,Oman,132.0,58.0,NaN
35826,36109,Michael Conway,1953-03-03,Sydney,New South Wales,AUS,Canada,132.0,48.0,NaN
28105,28315,Ana Manso,1966-03-07,Tarragona,Tarragona,ESP,Spain,132.0,31.0,NaN
4776,4794,Gabriel Ogun,1946-06-10,Epe,Lagos,NGR,Nigeria,133.0,48.0,NaN
126881,129286,Flávia Saraiva,1999-09-30,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,133.0,31.0,NaN
4505,4520,Peter Ayesu,1962-06-01,NaN,NaN,NaN,Malawi,135.0,51.0,NaN
101552,102450,Jana Labáková,1966-01-26,Detva,Banská Bystrica,SVK,Czechoslovakia,135.0,34.0,NaN
28762,28976,Choi Myong-Hui,1966-06-13,NaN,NaN,NaN,Democratic People's Republic of Korea,135.0,25.0,NaN
16507,16623,Stanley Smith,1952-08-20,NaN,NaN,NaN,Barbados,136.0,54.0,NaN
90538,91261,Crystal Gilmore,1983-04-08,Cambridge,Ontario,CAN,Canada,136.0,47.0,NaN
28042,28252,Lu Li,1976-08-30,Changsha,Hunan,CHN,People's Republic of China,136.0,30.0,NaN
28958,29172,Liubov Sheremeta,1980-01-17,Lviv,Lviv,UKR,Ukraine,136.0,30.0,NaN
28968,29182,Mariya Filatova,1961-07-19,Leninsk-Kuznetsky,Kemerovo,RUS,Soviet Union,136.0,30.0,NaN

In [38]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [39]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [54]:
olympics[(olympics["year"]>2000) & (olympics["discipline"]=="Tennis")]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
136,2004.0,Summer,Tennis,"Singles, Men (Olympic)",Fabrice Santoro,35,FRA,NaN,17.0,True,NaN
137,2004.0,Summer,Tennis,"Doubles, Men (Olympic)",Fabrice Santoro,35,FRA,Michaël Llodra,5.0,True,NaN
309,2004.0,Summer,Tennis,"Singles, Men (Olympic)",Tim Henman,99,GBR,NaN,33.0,True,NaN
537,2004.0,Summer,Tennis,"Doubles, Women (Olympic)",Christina Zachariadou,172,GRE,Eleni Daniilidou,17.0,True,NaN
793,2004.0,Summer,Tennis,"Doubles, Men (Olympic)",Mahesh Bhupathi,279,IND,Leander Paes,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
306308,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Hsieh Yu-Chieh,147671,TPE,Connie Hsu,17.0,True,NaN
306309,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Connie Hsu,147672,TPE,Hsieh Yu-Chieh,17.0,True,NaN
306310,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Giuliana Olmos,147673,MEX,Renata Zarazúa,17.0,True,NaN
306311,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Makoto Ninomiya,147674,JPN,Nao Hibino,17.0,True,NaN
306312,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Laura Pigossi,147675,BRA,Luísa Stefani,3.0,False,Bronze

In [55]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [68]:
bios[(bios["NOC"].str.contains("india", case=False)) & (bios["born_city"]=="Delhi")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19047,19181,Michael Gateley,1904-06-13,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,NaN
19053,19187,Arthur Hind,1904-10-20,Delhi,National Capital Territory of Delhi,IND,India,173.0,NaN,1991-11-20
19080,19214,Mirza Nasir-ud-Din Masood,1906-04-23,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,1991-09-21
19102,19236,Jaswant Rajput,1926-01-01,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,2015-01-28
19146,19281,Gindi Singh,1940-08-03,Delhi,National Capital Territory of Delhi,IND,India,171.0,65.0,2002-11-06
19173,19308,Randhir Singh Gentle,1922-09-22,Delhi,National Capital Territory of Delhi,IND,India Uganda,NaN,NaN,1981-09-25
34106,34370,Narinder Singh,1969-05-28,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,2016-02-05
58278,58692,Parkash Gian,1937-06-19,Delhi,National Capital Territory of Delhi,IND,India,165.0,67.0,NaN
58300,58714,Prem Nath,1951-07-01,Delhi,National Capital Territory of Delhi,IND,India,160.0,57.0,2015-06-02
58321,58736,Malwa Singh,1946-03-20,Delhi,National Capital Territory of Delhi,IND,India,137.0,52.0,1990-04-27
70911,71443,Surat Singh,1930-08-22,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,2021-06-11
80939,81590,Shailaja Kumar,1967-01-17,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,NaN
99707,100506,Shiva Keshavan,1981-08-25,Delhi,National Capital Territory of Delhi,IND,Independent Olympic Athletes India,183.0,85.0,NaN
106916,108030,Sujeet Maan,1978-12-15,Delhi,National Capital Territory of Delhi,IND,India,167.0,74.0,NaN
107001,108119,Anuj Kumar,1980-08-05,Delhi,National Capital Territory of Delhi,IND,India,175.0,84.0,NaN
109714,110918,Neha Ahuja,1981-09-27,Delhi,National Capital Territory of Delhi,IND,India,162.0,54.0,NaN
128069,130575,Manika Batra,1995-06-15,Delhi,National Capital Territory of Delhi,IND,India,179.0,63.0,NaN

In [63]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [69]:
results.query('type=="Winter" and noc=="IND" and year>2000')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
217117,2002.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,33.0,False,NaN
217118,2006.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,25.0,False,NaN
217119,2010.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,29.0,False,NaN
217121,2018.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,34.0,False,NaN
239992,2006.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Hira Lal,110832,IND,NaN,NaN,False,NaN
240205,2006.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Neha Ahuja,110918,IND,NaN,42.0,False,NaN
240206,2006.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Neha Ahuja,110918,IND,NaN,51.0,False,NaN
240285,2006.0,Winter,Cross Country Skiing (Skiing),"Sprint, Men (Olympic)",Bahadur Gurung Gupta,110945,IND,NaN,78.0,False,NaN
254418,2010.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Jamyang Namgial,118381,IND,NaN,81.0,False,NaN
256400,2010.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Tashi Lundup,118849,IND,NaN,83.0,False,NaN
273415,2014.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Himanshu Thakur,127893,IND,NaN,72.0,False,NaN
273416,2014.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Nadeem Iqbal,127894,IND,NaN,85.0,False,NaN
290801,2018.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Jagdish Singh,137354,IND,NaN,99.0,False,NaN
307483,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Arif Khan,148458,IND,NaN,45.0,False,NaN
307484,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Men (Olympic)",Arif Khan,148458,IND,NaN,NaN,False,NaN

In [71]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [73]:
coffee["price"]=4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [76]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [79]:
coffee["price"]=np.where(coffee["Coffee Type"]=="Espresso", 5.99, 6.99)
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [81]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [82]:
coffee.drop(columns=["price"])

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [83]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [85]:
coffee=coffee.rename(columns={"price": "Price"})
coffee.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [87]:
coffee["Revenue"]=coffee["Price"]*coffee["Units Sold"]
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   6.99   104.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   6.99   139.80
4  Wednesday    Espresso          35   5.99   209.65

In [88]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   6.99   104.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   6.99   139.80
4  Wednesday    Espresso          35   5.99   209.65

In [89]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [90]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [92]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [96]:
noc_regions=pd.read_csv('./data/noc_regions.csv')

In [97]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN