In [91]:
import pandas as pd 
import numpy as np 
coffee= pd.read_csv('./warmup-data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [92]:
results=pd.read_parquet('./data/results.parquet')

In [93]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [94]:
olympics=pd.read_excel('./data/olympics-data.xlsx', sheet_name='results')

In [95]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [96]:
bios=pd.read_csv('./data/bios.csv')

In [97]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [98]:
bios.loc[0:10,["name"]]

                       name
0     Jean-François Blanchy
1            Arnaud Boetsch
2              Jean Borotra
3           Jacques Brugnon
4              Albert Canet
5         Nicolas Chatelain
6             Patrick Chila
7              Henri Cochet
8             Marcel Cousin
9        Guy de la Chapelle
10  Élie, Comte de Lastours

In [99]:
olympics.iloc[3:15,[1,2,3]]

      type discipline                     event
3   Summer     Tennis  Doubles, Mixed (Olympic)
4   Summer     Tennis    Doubles, Men (Olympic)
5   Summer     Tennis    Singles, Men (Olympic)
6   Summer     Tennis    Doubles, Men (Olympic)
7   Summer     Tennis    Singles, Men (Olympic)
8   Summer     Tennis  Doubles, Mixed (Olympic)
9   Summer     Tennis    Doubles, Men (Olympic)
10  Summer     Tennis    Singles, Men (Olympic)
11  Summer     Tennis    Doubles, Men (Olympic)
12  Summer     Tennis    Doubles, Men (Olympic)
13  Summer     Tennis    Singles, Men (Olympic)
14  Summer     Tennis  Doubles, Mixed (Olympic)

In [100]:
olympics.iloc[0:10, 1:4]

     type discipline                     event
0  Summer     Tennis    Singles, Men (Olympic)
1  Summer     Tennis    Doubles, Men (Olympic)
2  Summer     Tennis    Singles, Men (Olympic)
3  Summer     Tennis  Doubles, Mixed (Olympic)
4  Summer     Tennis    Doubles, Men (Olympic)
5  Summer     Tennis    Singles, Men (Olympic)
6  Summer     Tennis    Doubles, Men (Olympic)
7  Summer     Tennis    Singles, Men (Olympic)
8  Summer     Tennis  Doubles, Mixed (Olympic)
9  Summer     Tennis    Doubles, Men (Olympic)

In [101]:
results.at[10,"athlete_id"]

np.int64(4)

In [102]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [103]:
bios.sort_values("height_cm").head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN
48662,49016,Nadia Fezzani,NaN,NaN,NaN,NaN,Libya,131.0,41.0,NaN
28105,28315,Ana Manso,1966-03-07,Tarragona,Tarragona,ESP,Spain,132.0,31.0,NaN
43257,43591,Said Al-Khatry,1947-01-01,NaN,NaN,NaN,Oman,132.0,66.0,NaN
35826,36109,Michael Conway,1953-03-03,Sydney,New South Wales,AUS,Canada,132.0,48.0,NaN
43259,43593,Khamis Al-Subhi,1954-01-01,NaN,NaN,NaN,Oman,132.0,58.0,NaN
4776,4794,Gabriel Ogun,1946-06-10,Epe,Lagos,NGR,Nigeria,133.0,48.0,NaN
126881,129286,Flávia Saraiva,1999-09-30,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,133.0,31.0,NaN
28762,28976,Choi Myong-Hui,1966-06-13,NaN,NaN,NaN,Democratic People's Republic of Korea,135.0,25.0,NaN
4505,4520,Peter Ayesu,1962-06-01,NaN,NaN,NaN,Malawi,135.0,51.0,NaN
101552,102450,Jana Labáková,1966-01-26,Detva,Banská Bystrica,SVK,Czechoslovakia,135.0,34.0,NaN
28042,28252,Lu Li,1976-08-30,Changsha,Hunan,CHN,People's Republic of China,136.0,30.0,NaN
90538,91261,Crystal Gilmore,1983-04-08,Cambridge,Ontario,CAN,Canada,136.0,47.0,NaN
28968,29182,Mariya Filatova,1961-07-19,Leninsk-Kuznetsky,Kemerovo,RUS,Soviet Union,136.0,30.0,NaN
28958,29172,Liubov Sheremeta,1980-01-17,Lviv,Lviv,UKR,Ukraine,136.0,30.0,NaN
16507,16623,Stanley Smith,1952-08-20,NaN,NaN,NaN,Barbados,136.0,54.0,NaN

In [104]:
bios.sort_values(["height_cm", "weight_kg"],ascending=[1, 0]).head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4515,4530,Lyton Mphande,1963-05-14,NaN,NaN,NaN,Malawi,127.0,62.0,NaN
28619,28832,Rosario Briones,1953-10-05,San Luis Potosí,San Luis Potosí,MEX,Mexico,127.0,42.0,NaN
4516,4531,Helman Palije,1967-06-24,NaN,NaN,NaN,Malawi,128.0,74.0,NaN
4517,4532,Boston Simbeye,1959-12-24,NaN,NaN,NaN,Malawi,130.0,67.0,NaN
4664,4681,Salvador Miranda,1949-09-13,NaN,NaN,NaN,Nicaragua,130.0,51.0,NaN
48662,49016,Nadia Fezzani,NaN,NaN,NaN,NaN,Libya,131.0,41.0,NaN
43257,43591,Said Al-Khatry,1947-01-01,NaN,NaN,NaN,Oman,132.0,66.0,NaN
43259,43593,Khamis Al-Subhi,1954-01-01,NaN,NaN,NaN,Oman,132.0,58.0,NaN
35826,36109,Michael Conway,1953-03-03,Sydney,New South Wales,AUS,Canada,132.0,48.0,NaN
28105,28315,Ana Manso,1966-03-07,Tarragona,Tarragona,ESP,Spain,132.0,31.0,NaN
4776,4794,Gabriel Ogun,1946-06-10,Epe,Lagos,NGR,Nigeria,133.0,48.0,NaN
126881,129286,Flávia Saraiva,1999-09-30,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,133.0,31.0,NaN
4505,4520,Peter Ayesu,1962-06-01,NaN,NaN,NaN,Malawi,135.0,51.0,NaN
101552,102450,Jana Labáková,1966-01-26,Detva,Banská Bystrica,SVK,Czechoslovakia,135.0,34.0,NaN
28762,28976,Choi Myong-Hui,1966-06-13,NaN,NaN,NaN,Democratic People's Republic of Korea,135.0,25.0,NaN
16507,16623,Stanley Smith,1952-08-20,NaN,NaN,NaN,Barbados,136.0,54.0,NaN
90538,91261,Crystal Gilmore,1983-04-08,Cambridge,Ontario,CAN,Canada,136.0,47.0,NaN
28042,28252,Lu Li,1976-08-30,Changsha,Hunan,CHN,People's Republic of China,136.0,30.0,NaN
28958,29172,Liubov Sheremeta,1980-01-17,Lviv,Lviv,UKR,Ukraine,136.0,30.0,NaN
28968,29182,Mariya Filatova,1961-07-19,Leninsk-Kuznetsky,Kemerovo,RUS,Soviet Union,136.0,30.0,NaN

In [105]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [106]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [107]:
olympics[(olympics["year"]>2000) & (olympics["discipline"]=="Tennis")]

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
136,2004.0,Summer,Tennis,"Singles, Men (Olympic)",Fabrice Santoro,35,FRA,NaN,17.0,True,NaN
137,2004.0,Summer,Tennis,"Doubles, Men (Olympic)",Fabrice Santoro,35,FRA,Michaël Llodra,5.0,True,NaN
309,2004.0,Summer,Tennis,"Singles, Men (Olympic)",Tim Henman,99,GBR,NaN,33.0,True,NaN
537,2004.0,Summer,Tennis,"Doubles, Women (Olympic)",Christina Zachariadou,172,GRE,Eleni Daniilidou,17.0,True,NaN
793,2004.0,Summer,Tennis,"Doubles, Men (Olympic)",Mahesh Bhupathi,279,IND,Leander Paes,4.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
306308,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Hsieh Yu-Chieh,147671,TPE,Connie Hsu,17.0,True,NaN
306309,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Connie Hsu,147672,TPE,Hsieh Yu-Chieh,17.0,True,NaN
306310,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Giuliana Olmos,147673,MEX,Renata Zarazúa,17.0,True,NaN
306311,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Makoto Ninomiya,147674,JPN,Nao Hibino,17.0,True,NaN
306312,2020.0,Summer,Tennis,"Doubles, Women (Olympic)",Laura Pigossi,147675,BRA,Luísa Stefani,3.0,False,Bronze

In [108]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [109]:
bios[(bios["NOC"].str.contains("india", case=False)) & (bios["born_city"]=="Delhi")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
19047,19181,Michael Gateley,1904-06-13,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,NaN
19053,19187,Arthur Hind,1904-10-20,Delhi,National Capital Territory of Delhi,IND,India,173.0,NaN,1991-11-20
19080,19214,Mirza Nasir-ud-Din Masood,1906-04-23,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,1991-09-21
19102,19236,Jaswant Rajput,1926-01-01,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,2015-01-28
19146,19281,Gindi Singh,1940-08-03,Delhi,National Capital Territory of Delhi,IND,India,171.0,65.0,2002-11-06
19173,19308,Randhir Singh Gentle,1922-09-22,Delhi,National Capital Territory of Delhi,IND,India Uganda,NaN,NaN,1981-09-25
34106,34370,Narinder Singh,1969-05-28,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,2016-02-05
58278,58692,Parkash Gian,1937-06-19,Delhi,National Capital Territory of Delhi,IND,India,165.0,67.0,NaN
58300,58714,Prem Nath,1951-07-01,Delhi,National Capital Territory of Delhi,IND,India,160.0,57.0,2015-06-02
58321,58736,Malwa Singh,1946-03-20,Delhi,National Capital Territory of Delhi,IND,India,137.0,52.0,1990-04-27
70911,71443,Surat Singh,1930-08-22,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,2021-06-11
80939,81590,Shailaja Kumar,1967-01-17,Delhi,National Capital Territory of Delhi,IND,India,NaN,NaN,NaN
99707,100506,Shiva Keshavan,1981-08-25,Delhi,National Capital Territory of Delhi,IND,Independent Olympic Athletes India,183.0,85.0,NaN
106916,108030,Sujeet Maan,1978-12-15,Delhi,National Capital Territory of Delhi,IND,India,167.0,74.0,NaN
107001,108119,Anuj Kumar,1980-08-05,Delhi,National Capital Territory of Delhi,IND,India,175.0,84.0,NaN
109714,110918,Neha Ahuja,1981-09-27,Delhi,National Capital Territory of Delhi,IND,India,162.0,54.0,NaN
128069,130575,Manika Batra,1995-06-15,Delhi,National Capital Territory of Delhi,IND,India,179.0,63.0,NaN

In [110]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [111]:
results.query('type=="Winter" and noc=="IND" and year>2000')

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
217117,2002.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,33.0,False,NaN
217118,2006.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,25.0,False,NaN
217119,2010.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,29.0,False,NaN
217121,2018.0,Winter,Luge,"Singles, Men (Olympic)",Shiva Keshavan,100506,IND,NaN,34.0,False,NaN
239992,2006.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Hira Lal,110832,IND,NaN,NaN,False,NaN
240205,2006.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Neha Ahuja,110918,IND,NaN,42.0,False,NaN
240206,2006.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Neha Ahuja,110918,IND,NaN,51.0,False,NaN
240285,2006.0,Winter,Cross Country Skiing (Skiing),"Sprint, Men (Olympic)",Bahadur Gurung Gupta,110945,IND,NaN,78.0,False,NaN
254418,2010.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Jamyang Namgial,118381,IND,NaN,81.0,False,NaN
256400,2010.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Tashi Lundup,118849,IND,NaN,83.0,False,NaN
273415,2014.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Himanshu Thakur,127893,IND,NaN,72.0,False,NaN
273416,2014.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Nadeem Iqbal,127894,IND,NaN,85.0,False,NaN
290801,2018.0,Winter,Cross Country Skiing (Skiing),"15 kilometres, Men (Olympic)",Jagdish Singh,137354,IND,NaN,99.0,False,NaN
307483,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Men (Olympic)",Arif Khan,148458,IND,NaN,45.0,False,NaN
307484,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Men (Olympic)",Arif Khan,148458,IND,NaN,NaN,False,NaN

In [112]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [113]:
coffee["price"]=4.99
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [114]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [115]:
coffee["price"]=np.where(coffee["Coffee Type"]=="Espresso", 5.99, 6.99)
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [116]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [117]:
coffee.drop(columns=["price"])

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [118]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [119]:
coffee=coffee.rename(columns={"price": "Price"})
coffee.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   5.99
1     Monday       Latte          15   6.99
2    Tuesday    Espresso          30   5.99
3    Tuesday       Latte          20   6.99
4  Wednesday    Espresso          35   5.99

In [120]:
coffee["Revenue"]=coffee["Price"]*coffee["Units Sold"]
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   6.99   104.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   6.99   139.80
4  Wednesday    Espresso          35   5.99   209.65

In [121]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   6.99   104.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   6.99   139.80
4  Wednesday    Espresso          35   5.99   209.65

In [122]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [123]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [124]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [125]:
noc_regions=pd.read_csv('./data/noc_regions.csv')

In [126]:
noc_regions.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [127]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [128]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [129]:
bios_new = bios.copy()

In [130]:
bios_new["First Name"]=bios["name"].str.split(" ").str[0]
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First Name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert

In [131]:
bios_new["date"]=pd.to_datetime(bios_new["born_date"])
bios_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
 10  First Name    145500 non-null  object
 11  date          143693 non-null  datetime64[us]
dtypes: datetime64[us](1), float64(2), int64(1), object(1), str(7)
memory usage: 20.7+ MB

In [132]:
bios_new["date_year"]=bios_new["date"].dt.year
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First Name,date,date_year
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0

In [133]:
bios["height_category"]=bios["height_cm"].apply(lambda x: "Short" if x<165 else ("Avg" if x<175 else "Tall"))
bios.head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Tall
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Tall
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Tall
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Tall
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,Tall
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18,Tall
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06,Tall
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Tall
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Tall
14,15,Damien Éloi,1969-07-04,Vire,Calvados,FRA,France,165.0,58.0,NaN,Avg
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06,Tall
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,Tall
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN,Tall
18,19,Maurice Germot,1882-11-15,Vichy,Allier,FRA,France,NaN,NaN,1958-08-06,Tall
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06,Tall

In [134]:
bios["height_category"]=bios["height_cm"].apply(lambda x: "Short" if x<165 else ("Avg" if x<175 else "Tall"))
bios.head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Tall
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Tall
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Tall
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Tall
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,Tall
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18,Tall
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06,Tall
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Tall
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Tall
14,15,Damien Éloi,1969-07-04,Vire,Calvados,FRA,France,165.0,58.0,NaN,Avg
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06,Tall
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,Tall
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN,Tall
18,19,Maurice Germot,1882-11-15,Vichy,Allier,FRA,France,NaN,NaN,1958-08-06,Tall
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06,Tall

In [135]:
def categorize_atheletes(x):
    if x["height_cm"]<175 and x["weight_kg"]<70:
        return "Light weight"
    elif x["height_cm"]<185 and x["weight_kg"]<80:
        return "Middle weight"
    else:
        return "Heavy weight"

bios["weight_category"]=bios.apply(categorize_atheletes, axis=1)

In [136]:
bios.head(20)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Tall,Middle weight
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Tall,Middle weight
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Tall,Heavy weight
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Tall,Heavy weight
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27,Tall,Heavy weight
10,11,"Élie, Comte de Lastours",1874-08-12,Orgeval,Yvelines,FRA,France,NaN,NaN,1932-11-18,Tall,Heavy weight
11,12,Max Decugis,1882-09-24,Paris XVIe,Paris,FRA,France,NaN,NaN,1978-09-06,Tall,Heavy weight
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Tall,Heavy weight
13,14,Étienne Durand,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN,Tall,Heavy weight
14,15,Damien Éloi,1969-07-04,Vire,Calvados,FRA,France,165.0,58.0,NaN,Avg,Light weight
15,16,Adrien Fauchier-Magnan,1873-11-19,Paris VIIIe,Paris,FRA,France,NaN,NaN,1965-08-06,Tall,Heavy weight
16,17,Guy Forget,1965-01-04,Casablanca,Casablanca-Settat,MAR,France,189.0,79.0,NaN,Tall,Heavy weight
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN,Tall,Middle weight
18,19,Maurice Germot,1882-11-15,Vichy,Allier,FRA,France,NaN,NaN,1958-08-06,Tall,Heavy weight
19,20,André Gobert,1890-09-30,Paris XVIIe,Paris,FRA,France,NaN,NaN,1951-12-06,Tall,Heavy weight

In [137]:
nocs=pd.read_csv('./data/noc_regions.csv')

In [138]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [139]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight

In [140]:
bios_new= pd.merge(bios, nocs, left_on="born_country", right_on="NOC", how="inner")
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,weight_category,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,GBR,UK,NaN

In [141]:
bios_new.rename(columns={"region": "born_country_full"}, inplace=True)
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,height_category,weight_category,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,GBR,UK,NaN

In [142]:
india=bios[bios["born_country"]=="IND"].copy()
gbr=bios[bios["born_country"]=="GBR"].copy()

In [143]:
india.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
80,81,George Caridia,1869-02-20,Kolkata (Calcutta),West Bengal,IND,Great Britain,NaN,NaN,1937-04-21,Tall,Heavy weight
101,102,Algernon Kingscote,1888-02-03,Bengaluru (Bangalore),Karnataka,IND,Great Britain,NaN,NaN,1964-12-21,Tall,Heavy weight
270,271,Nora Polley,1894-07-29,Budaun,Uttar Pradesh,IND,India,NaN,NaN,1988-01-01,Tall,Heavy weight
273,274,Zeeshan Ali,1970-01-01,Kolkata (Calcutta),West Bengal,IND,India,180.0,64.0,NaN,Tall,Middle weight
274,275,Anand Amritraj,1952-03-20,Chennai (Madras),Tamil Nadu,IND,India,185.0,77.0,NaN,Tall,Heavy weight

In [144]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26,Tall,Heavy weight
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10,Tall,Heavy weight
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22,Tall,Heavy weight
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN,Tall,Middle weight

In [145]:
new_df=pd.concat([india, gbr])
new_df.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
144811,148512,Benjamin Alexander,1983-05-08,London,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavy weight
144815,148517,Ashley Watson,1993-10-28,Peterborough,England,GBR,Jamaica,NaN,NaN,NaN,Tall,Heavy weight
145005,148716,Peder Kongshaug,2001-08-13,Wimbledon,England,GBR,Norway,184.0,86.0,NaN,Tall,Heavy weight
145319,149041,Axel Brown,1992-04-02,Harrogate,England,GBR,Trinidad and Tobago,NaN,NaN,NaN,Tall,Heavy weight
145388,149111,Jean-Luc Baker,1993-10-07,Burnley,England,GBR,United States,NaN,NaN,NaN,Tall,Heavy weight

In [146]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [147]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight

In [148]:
combined_df=pd.merge(results,bios,on="athlete_id", how="left")
combined_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,...,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,...,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight

In [149]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   6.99   104.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   6.99   139.80
4  Wednesday    Espresso          35   5.99   209.65

In [150]:
coffee.loc[5:8,["Coffee Type","Units Sold"]]

  Coffee Type  Units Sold
5       Latte          25
6    Espresso          40
7       Latte          30
8    Espresso          45

In [151]:
coffee.loc[5:8,"Units Sold"]=10
coffee.head

<bound method NDFrame.head of           Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25   5.99   149.75
1      Monday       Latte          15   6.99   104.85
2     Tuesday    Espresso          30   5.99   179.70
3     Tuesday       Latte          20   6.99   139.80
4   Wednesday    Espresso          35   5.99   209.65
5   Wednesday       Latte          10   6.99   174.75
6    Thursday    Espresso          10   5.99   239.60
7    Thursday       Latte          10   6.99   209.70
8      Friday    Espresso          10   5.99   269.55
9      Friday       Latte          35   6.99   244.65
10   Saturday    Espresso          45   5.99   269.55
11   Saturday       Latte          35   6.99   244.65
12     Sunday    Espresso          45   5.99   269.55
13     Sunday       Latte          35   6.99   244.65>

In [152]:
coffee.head

<bound method NDFrame.head of           Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25   5.99   149.75
1      Monday       Latte          15   6.99   104.85
2     Tuesday    Espresso          30   5.99   179.70
3     Tuesday       Latte          20   6.99   139.80
4   Wednesday    Espresso          35   5.99   209.65
5   Wednesday       Latte          10   6.99   174.75
6    Thursday    Espresso          10   5.99   239.60
7    Thursday       Latte          10   6.99   209.70
8      Friday    Espresso          10   5.99   269.55
9      Friday       Latte          35   6.99   244.65
10   Saturday    Espresso          45   5.99   269.55
11   Saturday       Latte          35   6.99   244.65
12     Sunday    Espresso          45   5.99   269.55
13     Sunday       Latte          35   6.99   244.65>

In [153]:
for index,rows in coffee.iterrows():
    print(index,rows["Coffee Type"])

0 Espresso
1 Latte
2 Espresso
3 Latte
4 Espresso
5 Latte
6 Espresso
7 Latte
8 Espresso
9 Latte
10 Espresso
11 Latte
12 Espresso
13 Latte

In [154]:
coffee[coffee["Coffee Type"]=="Espresso"]

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso          25   5.99   149.75
2     Tuesday    Espresso          30   5.99   179.70
4   Wednesday    Espresso          35   5.99   209.65
6    Thursday    Espresso          10   5.99   239.60
8      Friday    Espresso          10   5.99   269.55
10   Saturday    Espresso          45   5.99   269.55
12     Sunday    Espresso          45   5.99   269.55

In [155]:
coffee.loc[[2,3],"Units Sold"]=np.nan

In [156]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso        25.0   5.99   149.75
1      Monday       Latte        15.0   6.99   104.85
2     Tuesday    Espresso         NaN   5.99   179.70
3     Tuesday       Latte         NaN   6.99   139.80
4   Wednesday    Espresso        35.0   5.99   209.65
5   Wednesday       Latte        10.0   6.99   174.75
6    Thursday    Espresso        10.0   5.99   239.60
7    Thursday       Latte        10.0   6.99   209.70
8      Friday    Espresso        10.0   5.99   269.55
9      Friday       Latte        35.0   6.99   244.65
10   Saturday    Espresso        45.0   5.99   269.55
11   Saturday       Latte        35.0   6.99   244.65
12     Sunday    Espresso        45.0   5.99   269.55
13     Sunday       Latte        35.0   6.99   244.65

In [157]:
coffee[coffee["Units Sold"].isna()]

       Day Coffee Type  Units Sold  Price  Revenue
2  Tuesday    Espresso         NaN   5.99    179.7
3  Tuesday       Latte         NaN   6.99    139.8

In [158]:
coffee["Units Sold"].interpolate()

0     25.000000
1     15.000000
2     21.666667
3     28.333333
4     35.000000
5     10.000000
6     10.000000
7     10.000000
8     10.000000
9     35.000000
10    45.000000
11    35.000000
12    45.000000
13    35.000000
Name: Units Sold, dtype: float64

In [159]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso        25.0   5.99   149.75
1      Monday       Latte        15.0   6.99   104.85
2     Tuesday    Espresso         NaN   5.99   179.70
3     Tuesday       Latte         NaN   6.99   139.80
4   Wednesday    Espresso        35.0   5.99   209.65
5   Wednesday       Latte        10.0   6.99   174.75
6    Thursday    Espresso        10.0   5.99   239.60
7    Thursday       Latte        10.0   6.99   209.70
8      Friday    Espresso        10.0   5.99   269.55
9      Friday       Latte        35.0   6.99   244.65
10   Saturday    Espresso        45.0   5.99   269.55
11   Saturday       Latte        35.0   6.99   244.65
12     Sunday    Espresso        45.0   5.99   269.55
13     Sunday       Latte        35.0   6.99   244.65

In [163]:
coffee.fillna(coffee["Units Sold"].mean(), inplace=True)

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   5.99   149.75
1      Monday       Latte   15.000000   6.99   104.85
2     Tuesday    Espresso   25.833333   5.99   179.70
3     Tuesday       Latte   25.833333   6.99   139.80
4   Wednesday    Espresso   35.000000   5.99   209.65
5   Wednesday       Latte   10.000000   6.99   174.75
6    Thursday    Espresso   10.000000   5.99   239.60
7    Thursday       Latte   10.000000   6.99   209.70
8      Friday    Espresso   10.000000   5.99   269.55
9      Friday       Latte   35.000000   6.99   244.65
10   Saturday    Espresso   45.000000   5.99   269.55
11   Saturday       Latte   35.000000   6.99   244.65
12     Sunday    Espresso   45.000000   5.99   269.55
13     Sunday       Latte   35.000000   6.99   244.65

In [164]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   5.99   149.75
1      Monday       Latte   15.000000   6.99   104.85
2     Tuesday    Espresso   25.833333   5.99   179.70
3     Tuesday       Latte   25.833333   6.99   139.80
4   Wednesday    Espresso   35.000000   5.99   209.65
5   Wednesday       Latte   10.000000   6.99   174.75
6    Thursday    Espresso   10.000000   5.99   239.60
7    Thursday       Latte   10.000000   6.99   209.70
8      Friday    Espresso   10.000000   5.99   269.55
9      Friday       Latte   35.000000   6.99   244.65
10   Saturday    Espresso   45.000000   5.99   269.55
11   Saturday       Latte   35.000000   6.99   244.65
12     Sunday    Espresso   45.000000   5.99   269.55
13     Sunday       Latte   35.000000   6.99   244.65

In [165]:
coffee.head()

         Day Coffee Type  Units Sold  Price  Revenue
0     Monday    Espresso   25.000000   5.99   149.75
1     Monday       Latte   15.000000   6.99   104.85
2    Tuesday    Espresso   25.833333   5.99   179.70
3    Tuesday       Latte   25.833333   6.99   139.80
4  Wednesday    Espresso   35.000000   5.99   209.65

In [166]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Avg,Light weight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Avg,Light weight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Light weight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Avg,Heavy weight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavy weight

In [168]:
bios["born_city"].value_counts()

born_city
Budapest            1378
Moskva (Moscow)      883
Oslo                 708
Stockholm            629
Praha (Prague)       600
                    ...
Tsivilsk               1
Roth                   1
Romoos                 1
Dva Polya Artash       1
Dulwich Hill           1
Name: count, Length: 22368, dtype: int64

In [171]:
bios[bios["born_country"]=="IND"]["born_city"].value_counts().tail(10)

born_city
Idukki         1
Bodia          1
Nimriwali      1
Chakar         1
Ahmedabad      1
Sundernagar    1
Devsar         1
Bulandshahr    1
Khudan         1
Gulmarg        1
Name: count, dtype: int64

In [175]:
coffee.groupby(["Coffee Type"])["Price"].sum()

Coffee Type
Espresso    41.93
Latte       48.93
Name: Price, dtype: float64

In [176]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight
...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Avg,Light weight
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Avg,Light weight
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Light weight
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Avg,Heavy weight
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavy weight

In [ ]:
bios.groupby(["born_country"])["height_cm"].mean()

born_country
AFG       170.416667
AGU       186.000000
ALB       174.657895
ALG       176.489362
AND       172.096774
             ...
VIN       181.200000
Vienna    171.000000
YEM       169.000000
ZAM       173.192308
ZIM       173.540000
Name: height_cm, Length: 236, dtype: float64

In [181]:
bios.groupby(["born_country"])["weight_kg"].mean()

born_country
AFG       68.521739
AGU       78.000000
ALB       76.027778
ALG       68.043796
AND       67.451613
            ...
VIN       70.600000
Vienna    70.666667
YEM       55.250000
ZAM       68.400000
ZIM       67.061224
Name: weight_kg, Length: 236, dtype: float64

In [188]:
bios.groupby(["born_country", "born_city"]).agg({"height_cm": "mean", "weight_kg": "mean"})

                          height_cm  weight_kg
born_country born_city
AFG          Kabul       170.652174  69.136364
             Kandahar    165.000000  55.000000
AGU          South Hill  186.000000  78.000000
             The Valley         NaN        NaN
ALB          Dibër       159.000000  45.000000
...                             ...        ...
ZIM          Mutare      174.000000  70.000000
             Mutoko      186.000000  70.000000
             Norton      165.000000  68.000000
             Nyanga      171.500000  58.000000
             Rusape      172.000000  63.000000

[23000 rows x 2 columns]

In [189]:
bios.groupby(["born_country", "born_city"]).agg({"height_cm": "mean", "weight_kg": "mean"}).loc["IND"]

                  height_cm  weight_kg
born_city
Aarani                174.0       68.0
Abul Kharāna          175.0       61.0
Achalpur                NaN        NaN
Adra                  182.0        NaN
Agartala              151.0       47.0
...                     ...        ...
Wardha                178.0       85.0
Wayanad District      166.0       56.0
Wellington              NaN        NaN
Yamuna Nagar          180.0       69.0
Yamunanagar           159.0       61.0

[248 rows x 2 columns]

In [190]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [ ]:
results.groupby(["year", "noc", "discipline"])["medal"].count()

year    noc  discipline
1896.0  AUS  Athletics                           3
        AUT  Fencing                             3
             Swimming (Aquatics)                 2
        BEL  Fencing                             0
        BUL  Artistic Gymnastics (Gymnastics)    0
                                                ..
2022.0  USA  Skeleton (Bobsleigh)                0
             Ski Jumping (Skiing)                0
             Snowboarding (Skiing)               5
             Speed Skating (Skating)             4
        UZB  Alpine Skiing (Skiing)              0
Name: medal, Length: 32423, dtype: int64

In [193]:
results.groupby(["year", "discipline"])["event"].count()

year    discipline
1896.0  Artistic Gymnastics (Gymnastics)       128
        Athletics                              230
        Cycling Road (Cycling)                  57
        Cycling Track (Cycling)                  2
        Fencing                                 28
                                              ...
2022.0  Short Track Speed Skating (Skating)    300
        Skeleton (Bobsleigh)                    42
        Ski Jumping (Skiing)                   199
        Snowboarding (Skiing)                  285
        Speed Skating (Skating)                339
Name: event, Length: 1193, dtype: int64

In [ ]:
results.groupby(["year", "discipline"])["event"].nunique()

year    discipline
1896.0  Artistic Gymnastics (Gymnastics)       20
        Athletics                              42
        Cycling Road (Cycling)                  7
        Cycling Track (Cycling)                 1
        Fencing                                12
                                               ..
2022.0  Short Track Speed Skating (Skating)     9
        Skeleton (Bobsleigh)                    2
        Ski Jumping (Skiing)                    5
        Snowboarding (Skiing)                  11
        Speed Skating (Skating)                14
Name: event, Length: 1193, dtype: int64

In [195]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   5.99   149.75
1      Monday       Latte   15.000000   6.99   104.85
2     Tuesday    Espresso   25.833333   5.99   179.70
3     Tuesday       Latte   25.833333   6.99   139.80
4   Wednesday    Espresso   35.000000   5.99   209.65
5   Wednesday       Latte   10.000000   6.99   174.75
6    Thursday    Espresso   10.000000   5.99   239.60
7    Thursday       Latte   10.000000   6.99   209.70
8      Friday    Espresso   10.000000   5.99   269.55
9      Friday       Latte   35.000000   6.99   244.65
10   Saturday    Espresso   45.000000   5.99   269.55
11   Saturday       Latte   35.000000   6.99   244.65
12     Sunday    Espresso   45.000000   5.99   269.55
13     Sunday       Latte   35.000000   6.99   244.65

In [200]:
bios["born_date"]=pd.to_datetime(bios["born_date"])
bios["month_born"]=bios["born_date"].dt.month
bios["year_born"]=bios["born_date"].dt.year
bios.groupby([bios["year_born"], bios["month_born"]])["name"].count().reset_index().sort_values(ascending=False, by="name")

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

In [ ]:
bios.groupby([bios["year_born"]])["name"].count().sort_values(ascending=False)

year_born
1972.0    2231
1985.0    2227
1973.0    2216
1971.0    2205
1970.0    2174
          ...
1837.0       1
1833.0       1
1839.0       1
1845.0       1
2009.0       1
Name: name, Length: 177, dtype: int64

In [204]:
coffee

          Day Coffee Type  Units Sold  Price  Revenue
0      Monday    Espresso   25.000000   5.99   149.75
1      Monday       Latte   15.000000   6.99   104.85
2     Tuesday    Espresso   25.833333   5.99   179.70
3     Tuesday       Latte   25.833333   6.99   139.80
4   Wednesday    Espresso   35.000000   5.99   209.65
5   Wednesday       Latte   10.000000   6.99   174.75
6    Thursday    Espresso   10.000000   5.99   239.60
7    Thursday       Latte   10.000000   6.99   209.70
8      Friday    Espresso   10.000000   5.99   269.55
9      Friday       Latte   35.000000   6.99   244.65
10   Saturday    Espresso   45.000000   5.99   269.55
11   Saturday       Latte   35.000000   6.99   244.65
12     Sunday    Espresso   45.000000   5.99   269.55
13     Sunday       Latte   35.000000   6.99   244.65

In [208]:
coffee["revenue diff"]=coffee["Revenue"]-coffee["Revenue"].shift(2)
coffee

          Day Coffee Type  Units Sold  Price  Revenue  revenue diff
0      Monday    Espresso   25.000000   5.99   149.75           NaN
1      Monday       Latte   15.000000   6.99   104.85           NaN
2     Tuesday    Espresso   25.833333   5.99   179.70         29.95
3     Tuesday       Latte   25.833333   6.99   139.80         34.95
4   Wednesday    Espresso   35.000000   5.99   209.65         29.95
5   Wednesday       Latte   10.000000   6.99   174.75         34.95
6    Thursday    Espresso   10.000000   5.99   239.60         29.95
7    Thursday       Latte   10.000000   6.99   209.70         34.95
8      Friday    Espresso   10.000000   5.99   269.55         29.95
9      Friday       Latte   35.000000   6.99   244.65         34.95
10   Saturday    Espresso   45.000000   5.99   269.55          0.00
11   Saturday       Latte   35.000000   6.99   244.65          0.00
12     Sunday    Espresso   45.000000   5.99   269.55          0.00
13     Sunday       Latte   35.000000   6.99   244.65          0.00

In [213]:
coffee["pct change"]=coffee["Revenue"].pct_change(2)*100
coffee

,Day,Coffee Type,Units Sold,Price,Revenue,revenue diff,pct change
0,Monday,Espresso,25.000000,5.99,149.75,NaN,NaN
1,Monday,Latte,15.000000,6.99,104.85,NaN,NaN
2,Tuesday,Espresso,25.833333,5.99,179.70,29.95,20.000000
3,Tuesday,Latte,25.833333,6.99,139.80,34.95,33.333333
4,Wednesday,Espresso,35.000000,5.99,209.65,29.95,16.666667
5,Wednesday,Latte,10.000000,6.99,174.75,34.95,25.000000
6,Thursday,Espresso,10.000000,5.99,239.60,29.95,14.285714
7,Thursday,Latte,10.000000,6.99,209.70,34.95,20.000000
8,Friday,Espresso,10.000000,5.99,269.55,29.95,12.500000
9,Friday,Latte,35.000000,6.99,244.65,34.95,16.666667
10,Saturday,Espresso,45.000000,5.99,269.55,0.00,0.000000
11,Saturday,Latte,35.000000,6.99,244.65,0.00,0.000000
12,Sunday,Espresso,45.000000,5.99,269.55,0.00,0.000000
13,Sunday,Latte,35.000000,6.99,244.65,0.00,0.000000

In [216]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [217]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category,month_born,year_born
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,12.0,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,4.0,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,8.0,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,5.0,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,4.0,1878.0

In [218]:
olympics.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [228]:
olympics["ranking"]=olympics["place"].rank(ascending=False)
olympics

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,ranking
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN,82697.5
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN,40367.5
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN,154185.0
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN,221366.5
...,...,...,...,...,...,...,...,...,...,...,...,...
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN,52571.0
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN,48125.5
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN,104951.5
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN,57716.0

In [229]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category,month_born,year_born
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,12.0,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,4.0,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,8.0,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,5.0,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,4.0,1878.0

In [232]:
bios["rank"]=bios["height_cm"].rank(method='dense', ascending=False)
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category,month_born,year_born,rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,12.0,1886.0,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,4.0,1969.0,41.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,8.0,1898.0,41.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,5.0,1895.0,56.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,4.0,1878.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Avg,Light weight,1.0,2002.0,57.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Avg,Light weight,9.0,1999.0,56.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Light weight,5.0,1998.0,61.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Avg,Heavy weight,5.0,1899.0,58.0
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavy weight,7.0,1913.0,NaN

In [ ]:
bios["country_rank"]=bios.groupby(["NOC"])["height_cm"].rank(ascending=False)
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category,month_born,year_born,rank,country_rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,12.0,1886.0,NaN,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,4.0,1969.0,41.0,950.5
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,8.0,1898.0,41.0,950.5
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,5.0,1895.0,56.0,3196.5
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,4.0,1878.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Avg,Light weight,1.0,2002.0,57.0,99.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Avg,Light weight,9.0,1999.0,56.0,91.0
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Light weight,5.0,1998.0,61.0,115.0
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Avg,Heavy weight,5.0,1899.0,58.0,3394.5
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavy weight,7.0,1913.0,NaN,NaN

In [237]:
bios["region rank"]=(bios.groupby(["born_region"])["height_cm"].rank(ascending=False))
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,weight_category,month_born,year_born,rank,country_rank,region rank
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavy weight,12.0,1886.0,NaN,NaN,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Tall,Middle weight,4.0,1969.0,41.0,950.5,11.5
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Tall,Middle weight,8.0,1898.0,41.0,950.5,9.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Avg,Light weight,5.0,1895.0,56.0,3196.5,291.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavy weight,4.0,1878.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Avg,Light weight,1.0,2002.0,57.0,99.0,143.0
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Avg,Light weight,9.0,1999.0,56.0,91.0,626.5
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short,Light weight,5.0,1998.0,61.0,115.0,20.5
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Avg,Heavy weight,5.0,1899.0,58.0,3394.5,10.5
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall,Heavy weight,7.0,1913.0,NaN,NaN,NaN